version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: beatrice
      POSTGRES_PASSWORD: Ivy01234@
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: